# packages in environment at C:\Users\pasca\Anaconda3\envs\toxblock_env:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl  
absl-py                   0.9.0            py37hc8dfbb8_1    conda-forge
astor                     0.7.1                      py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
autograd                  1.3                      pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
blas                      1.0                         mkl  
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py37h4ab8f01_1000    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
cachetools                4.1.0                      py_1    conda-forge
catalogue                 1.0.0                      py_0    conda-forge
certifi                   2020.4.5.2       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37ha419a9e_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              2.9.2            py37h26f1ce3_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cymem                     2.0.3            py37h1834ac0_2    conda-forge
cython-blis               0.4.1            py37h8055547_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
en-core-web-sm            2.2.5                    pypi_0    pypi
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
freetype                  2.10.2               hd328e21_0    conda-forge
future                    0.18.2                   pypi_0    pypi
gast                      0.2.2                      py_0    conda-forge
google-auth               1.17.2                     py_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpcio                    1.27.2           py37h351948d_0  
h5py                      2.10.0          nompi_py37h422b98e_102    conda-forge
hdf5                      1.10.5          nompi_ha405e13_1104    conda-forge
icc_rt                    2019.0.0             h0cc432a_1  
icu                       64.2                 he025d50_1    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.6.1            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.1                         0    conda-forge
intel-openmp              2019.4                      245  
ipykernel                 5.3.0            py37h5ca1d4c_0    conda-forge
ipython                   7.15.0           py37hc8dfbb8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.17.1           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.15.1                     py_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
kiwisolver                1.2.0            py37heaa310e_0    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libmklml                  2019.0.5                      0  
libpng                    1.6.37               hfe6a214_1    conda-forge
libprotobuf               3.12.3               h7bd577a_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
llvmlite                  0.32.1           py37hc8dfbb8_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
markdown                  3.2.2                      py_0    conda-forge
markupsafe                1.1.1            py37h8055547_1    conda-forge
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py37h911224e_0    conda-forge
mistune                   0.8.4           py37h8055547_1001    conda-forge
mkl                       2019.4                      245  
mkl-service               2.3.0            py37hfa6e2cd_0    conda-forge
mkl_fft                   1.1.0            py37hc8d92b1_1    conda-forge
mkl_random                1.1.0            py37he350917_0    conda-forge
more-itertools            8.4.0                      py_0    conda-forge
msys2-conda-epoch         20160418                      1  
murmurhash                1.0.0            py37h63f7a3c_0    conda-forge
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
numba                     0.49.1           py37h47e9c7a_0  
numpy                     1.18.1           py37h93ca92e_0  
numpy-base                1.18.1           py37hc3f5095_1  
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1g               he774522_0    conda-forge
opt_einsum                3.2.1                      py_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.0.3            py37h47e9c7a_0  
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pip                       20.1.1                   pypi_0    pypi
plac                      0.9.6                      py_1    conda-forge
pluggy                    0.13.1           py37hc8dfbb8_1    conda-forge
preshed                   3.0.2            py37h1834ac0_3    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_1    conda-forge
prompt_toolkit            3.0.5                         1    conda-forge
protobuf                  3.12.3           py37h9303ea8_0    conda-forge
py                        1.8.2              pyh9f0ad1d_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h1834ac0_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyreadline                2.1                   py37_1001    conda-forge
pyrsistent                0.16.0           py37h8055547_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pytest                    5.4.3            py37hc8dfbb8_0    conda-forge
python                    3.7.7                h81c818b_4  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywin32                   227              py37hfa6e2cd_0    conda-forge
pywinpty                  0.5.7                    py37_0    conda-forge
pyzmq                     19.0.1           py37h453f00a_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtconsole                 4.7.4              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
rsa                       4.6                pyh9f0ad1d_0    conda-forge
scikit-learn              0.22.1           py37h6288b17_0  
scipy                     1.3.1            py37h29ff71c_0    conda-forge
seaborn                   0.10.1                        1    conda-forge
seaborn-base              0.10.1                     py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                47.3.1           py37hc8dfbb8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
spacy                     2.2.4            py37h1fb7aa8_1    conda-forge
sparse                    0.10.0                     py_0    conda-forge
sqlite                    3.32.2               h2a8f88b_0  
srsly                     1.0.2            py37h1834ac0_0    conda-forge
statsmodels               0.11.1           py37h4ab8f01_2    conda-forge
tbb                       2020.1               he980bc4_0    conda-forge
tensorboard               2.1.1                      py_1    conda-forge
tensorflow                2.1.0           mkl_py37ha977152_0  
tensorflow-base           2.1.0           mkl_py37h230818c_0  
tensorflow-estimator      2.1.0              pyhd54b08b_0  
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thinc                     7.4.0            py37heaa310e_2    conda-forge
tornado                   6.0.4            py37hfa6e2cd_0    conda-forge
tqdm                      4.46.1             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wasabi                    0.6.0                      py_0    conda-forge
wcwidth                   0.2.4              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.1                     py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1           py37h8055547_1    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
